version: 2
jobs:
  build:
    working_directory: ~/lib
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            sudo pip install pipenv
            sudo pipenv install --dev --system
      - run:
          name: Linting codes
          command: |
            temp=$(mktemp)
            if [ "$(yapf -dr . 2&>1 | tee $temp | wc -l)" != "0" ]
            then
              cat $temp
              exit 1
            fi
